### PR TITLE
Fix the extension popup

### PR DESCRIPTION
**Pull request by SpookyKipper**
This fixes the extension popup not appearing, using the handleClick function at https://github.com/daijro/Clipboard2File-Chrome/blob/master/app/content/all_frames.js

### CODE REVIEW

**Comment by david-clipboard2file** [comment]
I don't understand what these changes are trying to accomplish. The description links to a random fork and the code changes remove important logic for handling shadow DOM.

Can you please explain your goal?

**Comment by SpookyKipper** [comment]
Hello, the current version on the addons store does not seem to be working, but by applying this fix seems to fix it

Issue #12 was also from a year ago and looks like not only me is experiencing issues

**Comment by SpookyKipper** [comment]
Hmm.. It seems to work for me now

**Comment by david-clipboard2file** [comment]
Issue #12 was filed before the code changes you're trying to revert were introduced. There are lot of reasons why the extension may not work. 

Listed in order of likelihood:
1. User forgot to enable dom.events.asyncClipboard.clipboardItem in about:config
2. User is in private browsing mode, and forgot to enable the extension in private browsing
3. Sometimes the browser needs to be restarted for the extension to work

Are you sure you've verified all of these? 

And if the extension is working on some websites but not others, please link to a website where it does not work and one where it does work, thank you.

**Comment by SpookyKipper** [comment]
I may did not restart the browser properly (maybe i missed a window when I tried to restart it), I did restart my device yesterday
I guess the PR wasn't needed that
Sorry for that

**Comment by david-clipboard2file** [comment]
Future contributions are welcome. At least you tried, most people never do.

**Pull request closed without merging**
